name: Auto Inject IPA and Tweak

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: 'URL to the decrypted IPA file'
        required: true
        type: string
      deb_url:
        description: 'URL to the Tweak (.deb) file'
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Azule directly
        run: |
          # Tải trực tiếp công cụ Azule chính hãng
          sudo curl -L https://raw.githubusercontent.com/Al4EP/Azule/main/azule -o /usr/local/bin/azule
          sudo chmod +x /usr/local/bin/azule

      - name: Download Files from Inputs
        run: |
          echo "Đang tải file IPA từ link bạn nhập..."
          curl -L -o input.ipa "${{ github.event.inputs.ipa_url }}"
          
          echo "Tạo thư mục tweaks và tải file .deb..."
          mkdir -p tweaks
          curl -L -o tweaks/tweak.deb "${{ github.event.inputs.deb_url }}"

      - name: Run Injection
        run: |
          azule -i input.ipa -o Output_App.ipa -f tweaks/*.deb -v

      - name: Upload Patched IPA
        uses: actions/upload-artifact@v4
        with:
          name: Final-Patched-IPA
          path: Output_App.ipa
